version: '3.8'

services:
    postgres:
        image: postgres:15
        container_name: postgres
        environment:
            POSTGRES_DB: YOUR_DB
            POSTGRES_USER: YOUR_UNAME
            POSTGRES_PASSWORD: YOUR_PWD
        ports:
            - "5432:5432"
        networks:
            - jobapp-network
        volumes:
            - postgres-data:/var/lib/postgresql/data

    jobapp:
        build: .
        container_name: jobapp
        ports:
            - "8085:8085"
        depends_on:
            - postgres
        environment:
            SPRING_DATASOURCE_URL: YOUR_URL
            SPRING_DATASOURCE_USERNAME: YOUR_UNAME
            SPRING_DATASOURCE_PASSWORD: YOUR_PWD
            SPRING_JPA_HIBERNATE_DDL_AUTO: update
            SPRING_PROFILES_ACTIVE: docker
        networks:
            - jobapp-network

networks:
    jobapp-network:

volumes:
    postgres-data:
