package com.vishwa.firstjobapp.company;

import com.vishwa.firstjobapp.job.Job;
import com.vishwa.firstjobapp.review.Review;
import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.AllArgsConstructor; // Import Lombok's AllArgsConstructor
import lombok.Data;             // Import Lombok's Data
import lombok.NoArgsConstructor;   // Import Lombok's NoArgsConstructor

import java.util.List;

@Entity
@Data                  // Generates getters, setters, toString(), equals(), and hashCode()
@NoArgsConstructor     // Generates a no-argument constructor (required by JPA)
@AllArgsConstructor    // Generates a constructor with all fields as arguments
public class Company {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long companyId;
    private String name;
    private String description;

    @JsonIgnore
    //Orphan true removes the job from the list and db. For List is remove method and db is delete method.
    @OneToMany(mappedBy = "company", cascade = CascadeType.ALL, orphanRemoval = true) // Added cascade and orphanRemoval for better relationship management
    private List<Job> jobs;

    @OneToMany(mappedBy = "company", cascade = CascadeType.ALL, orphanRemoval = true) // Added cascade and orphanRemoval for better relationship management
    private List<Review> reviews;

    // All constructors, getters, and setters are now generated by Lombok!
    // No explicit code needed for them.
}